%YAML 1.1
---
language: d
sudo: false
before_install:
- pip install --user codecov
- dub fetch packageversion
script: ['dub test --compiler=${DC} --coverage', 'dub build --compiler=${DC} --build=ddox']
after_success:
- codecov
d: [dmd, ldc]
addons:
  apt:
    packages: [libevent-dev]
